services:
  php-fpm:
    build: docker/php-fpm
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - '.:/var/www/html'
      - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
    networks:
      - default

  nginx:
    image: 'nginx:1.23.3-alpine'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar.rule=Host(`calendar.prozesshub.eu`)"
      - "traefik.http.services.calendar.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_web

  mysql:
    image: 'mysql:8.0'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - default

  phpmyadmin:
    image: 'phpmyadmin:5.2.1'
    environment:
      - 'PMA_HOST=mysql'
      - 'UPLOAD_LIMIT=102400K'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.calendar.prozesshub.eu`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_web

  mailpit:
    image: 'axllent/mailpit:v1.7'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.calendar.prozesshub.eu`)"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
    networks:
      - default
      - traefik_web

  swagger-ui:
    platform: linux/amd64
    image: swaggerapi/swagger-ui:v5.10.5
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swagger.rule=Host(`swagger.calendar.prozesshub.eu`)"
      - "traefik.http.services.swagger.loadbalancer.server.port=8080"
    networks:
      - default
      - traefik_web
  
  baikal:
    image: ckulka/baikal:0.10.1-apache
    volumes:
      - ./docker/baikal:/var/www/html
      - ./docker/baikal/config:/var/www/baikal/config
      - ./docker/baikal/data:/var/www/baikal/Specific
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.rule=Host(`baikal.calendar.prozesshub.eu`)"
      - "traefik.http.services.baikal.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_web

networks:
  default:
  traefik_web:
    external: true
